### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by HakkaMc** [stevensacks/eslint-plugin-sort-react-dependency-arrays#2]
It uses the JavaScript's localeCompare function so on different environments the result can be different.  So it would be nice to support a locale setting, e.g. adding locale to the .env file.

.env file example:
```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
```

sort.js enhancing:
```
const env = process.env;
const language = env.LANG || env.LANGUAGE || env.LC_ALL || env.LC_MESSAGES;
let languageCode = undefined

if(language && language.toString().trim()){
      languageCode = language.toString().trim().split('_')[0]
}
...
...
...
.sort((a, b) =>
    a.name
        .toLowerCase()
        .localeCompare(b.name.toLowerCase(), languageCode)
);
```

**Comment by stevensacks** [comment]
I’ve decided to discontinue this plugin because its behavior is covered by this other one, which has other helpful rules, too. 

https://github.com/gajus/eslint-plugin-canonical
